name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  # schedule:
  #  - cron: 30 16 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  # PUSH_KEY: ${{ secrets.PUSH_KEY }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt
                
            - name: Send Email
             
              
  uses: dawidd6/action-send-mail@v4
  with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    #
    #  * smtp://user:password@server:port
    #  * smtp+starttls://user:password@server:port
    #connection_url: ${{secrets.MAIL_CONNECTION}}
    # Required mail server address if not connection_url:
    server_address: smtp.qiye.aliyun.com
    # Server port, default 25:
    server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
    secure: true
    # Optional (recommended) mail server username:
    username: no-reply@xingyuexi.eu.org
    # Optional (recommended) mail server password:
    password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
    subject: 京东
    # Required recipients' addresses:
    to: admin@xingyuexi.eu.org,
    # Required sender full name (address can be skipped):
    from: no-reply@xingyuexi.eu.org  # <user@example.com>
    # Optional plain body:
    #body: Build job of ${{github.repository}} completed successfully!
    # Optional HTML body read from file:
    html_body: file://result.txt
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
    convert_markdown: true
    # Optional attachments:
    attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
    priority: low
    # Optional nodemailerlog: true/false
    nodemailerlog: false
    # Optional nodemailerdebug: true/false if true lognodem will also be set true
    nodemailerdebug: false
             
        
